---
name: Lint Code Base

on: push
  # push:
  #   branches-ignore: [master, main]
  #   # Remove the line above to run when pushing to master
  # pull_request:
  #   branches: [master, main]

jobs:
  build:
    name: PR verification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run linters
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main